import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'language_provider.dart';

class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    final langProvider = Provider.of<LanguageProvider>(context);
    return AppLocalizations(langProvider.currentLanguageCode);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Study Timetable',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account? Register",
      'already_have_account': 'Already have an account? Login',
      'send_reset_link': 'Send Reset Link',
      'email_verification': 'Email Verification',
      'verification_sent': 'A verification email has been sent to your address. Please verify to continue.',
      'resend_email': 'Resend Email',
      'check_status': 'I have verified',
      'name': 'Full Name',
      'select_goal': 'Select Competitive Exam Goal',
      'logout': 'Logout',
      'language': 'Language',
      'select_language': 'Select Language',
      'dashboard': 'Dashboard',
      'timetable_card': 'Timetable',
      'timetable_desc': 'Smart exam study schedule',
      'exams_card': 'Exams',
      'exams_desc': 'CBT Practice & Mock Tests',
      'books_card': 'Books',
      'books_desc': 'Download syllabus-wise books',
      'profile_card': 'Profile',
      'profile_desc': 'Performance metrics & stats',
      'weekly_performance': 'Weekly Performance',
      'result_analysis': 'Weekly Result Analysis',
      'accuracy': 'Accuracy Percentage',
      'total_exams': 'Total Exams Attempted',
      'weak_subjects': 'Weak Subjects',
      'strong_subjects': 'Strong Subjects',
      'streak': 'Study Streak',
      'days': 'Days',
      'test_marks': 'Latest Test Marks',
      'goal': 'Goal',
      'select_start_date': 'Select Start Date',
      'select_end_date': 'Select End Date',
      'generate_timetable': 'Generate Dynamic Timetable',
      'no_timetable': 'No timetable generated yet. Select dates and generate one!',
      'date': 'Date',
      'time': 'Time',
      'subject': 'Subject',
      'topic': 'Topic',
      'police_books': 'Police Books',
      'banking_books': 'Banking Books',
      'railway_books': 'Railway Books',
      'ssc_books': 'SSC Books',
      'groups_books': 'Groups Books',
      'tspsc_books': 'TSPSC Books',
      'appsc_books': 'APPSC Books',
      'download': 'Download',
      'downloading': 'Downloading...',
      'downloaded': 'Downloaded',
      'read': 'Read Book',
      'favorites': 'Favorites Only',
      'cbt_interface': 'CBT Exam Interface',
      'remaining_time': 'Remaining Time',
      'submit_exam': 'Submit Exam',
      'question': 'Question',
      'explanation': 'Detailed Explanation',
      'instant_result': 'Instant Exam Result',
      'correct_answers': 'Correct Answers',
      'wrong_answers': 'Wrong Answers',
      'score': 'Score',
      'pass_fail': 'Result Status',
      'admin_panel': 'Admin Control Panel',
      'add_question': 'Add Question',
      'add_book': 'Add Book',
      'add_timetable': 'Add Timetable Template',
      'user_analytics': 'User Analytics',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'invalid_email': 'Enter a valid email address',
      'short_password': 'Password must be at least 6 characters',
      'passwords_dont_match': 'Passwords do not match',
      'field_required': 'This field is required',
      'admin_only': 'Admin view. Manage syllabus assets here.',
      'user_name': 'Student Profile',
      'streak_active': 'Streak Active!',
      'back_to_dashboard': 'Back to Dashboard',
      'next': 'Next',
      'previous': 'Previous',
    },
    'te': {
      'app_title': 'స్టడీ టైమ్‌టేబుల్',
      'login': 'లాగిన్',
      'register': 'రిజిస్టర్',
      'email': 'ఈమెయిల్ చిరునామా',
      'password': 'పాస్‌వర్డ్',
      'confirm_password': 'పాస్‌వర్డ్ నిర్ధారణ',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'dont_have_account': 'ఖాతా లేదా? రిజిస్టర్ అవ్వండి',
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి',
      'send_reset_link': 'రీసెట్ లింక్ పంపండి',
      'email_verification': 'ఈమెయిల్ ధృవీకరణ',
      'verification_sent': 'ధృవీకరణ ఈమెయిల్ మీ చిరునామాకు పంపబడింది. కొనసాగడానికి దయచేసి ధృవీకరించండి.',
      'resend_email': 'ఈమెయిల్ మళ్లీ పంపండి',
      'check_status': 'నేను ధృవీకరించాను',
      'name': 'పూర్తి పేరు',
      'select_goal': 'పోటీ పరీక్ష లక్ష్యాన్ని ఎంచుకోండి',
      'logout': 'లాగ్ అవుట్',
      'language': 'భాష',
      'select_language': 'భాషను ఎంచుకోండి',
      'dashboard': 'డాష్‌బోర్డ్',
      'timetable_card': 'టైమ్‌టేబుల్',
      'timetable_desc': 'స్మార్ట్ అధ్యయన ప్రణాళిక',
      'exams_card': 'పరీక్షలు',
      'exams_desc': 'CBT సాధన & మాక్ టెస్ట్‌లు',
      'books_card': 'పుస్తకాలు',
      'books_desc': 'సిలబస్ పుస్తకాలు డౌన్‌లోడ్ చేసుకోండి',
      'profile_card': 'ప్రొఫైల్',
      'profile_desc': 'పనితీరు కొలతలు & గణాంకాలు',
      'weekly_performance': 'వారపు పనితీరు',
      'result_analysis': 'వారపు ఫలితాల విశ్లేషణ',
      'accuracy': 'ఖచ్చితత్వ శాతం',
      'total_exams': 'రాసిన మొత్తం పరీక్షలు',
      'weak_subjects': 'బలహీనమైన సబ్జెక్టులు',
      'strong_subjects': 'బలమైన సబ్జెక్టులు',
      'streak': 'అధ్యయన స్ట్రీక్',
      'days': 'రోజులు',
      'test_marks': 'చివరి పరీక్ష మార్కులు',
      'goal': 'లక్ష్యం',
      'select_start_date': 'ప్రారంభ తేదీని ఎంచుకోండి',
      'select_end_date': 'ముగింపు తేదీని ఎంచుకోండి',
      'generate_timetable': 'డైనమిక్ టైమ్‌టేబుల్ సృష్టించు',
      'no_timetable': 'ఇంకా టైమ్‌టేబుల్ సృష్టించబడలేదు. తేదీలను ఎంచుకుని సృష్టించండి!',
      'date': 'తేదీ',
      'time': 'సమయం',
      'subject': 'సబ్జెక్టు',
      'topic': 'టాపిక్',
      'police_books': 'పోలీస్ పుస్తకాలు',
      'banking_books': 'బ్యాంకింగ్ పుస్తకాలు',
      'railway_books': 'రైల్వే పుస్తకాలు',
      'ssc_books': 'SSC పుస్తకాలు',
      'groups_books': 'గ్రూప్స్ పుస్తకాలు',
      'tspsc_books': 'TSPSC పుస్తకాలు',
      'appsc_books': 'APPSC పుస్తకాలు',
      'download': 'డౌన్‌లోడ్',
      'downloading': 'డౌన్‌లోడ్ అవుతోంది...',
      'downloaded': 'డౌన్‌లోడ్ చేయబడింది',
      'read': 'చదవండి',
      'favorites': 'ఇష్టమైనవి మాత్రమే',
      'cbt_interface': 'CBT పరీక్షా ఇంటర్ఫేస్',
      'remaining_time': 'మిగిలిన సమయం',
      'submit_exam': 'పరీక్షను సమర్పించు',
      'question': 'ప్రశ్న',
      'explanation': 'వివరణాత్మక వివరణ',
      'instant_result': 'తక్షణ పరీక్ష ఫలితం',
      'correct_answers': 'సరైన సమాధానాలు',
      'wrong_answers': 'తప్పు సమాధానాలు',
      'score': 'స్కోరు',
      'pass_fail': 'ఫలితం స్థితి',
      'admin_panel': 'అడ్మిన్ నియంత్రణ ప్యానెల్',
      'add_question': 'ప్రశ్నను జోడించు',
      'add_book': 'పుస్తకాన్ని జోడించు',
      'add_timetable': 'టైమ్‌టేబుల్ టెంప్లేట్ జోడించు',
      'user_analytics': 'వినియోగదారు విశ్లేషణలు',
      'save': 'భద్రపరచు',
      'delete': 'తొలగించు',
      'edit': 'సవరించు',
      'invalid_email': 'చెల్లుబాటు అయ్యే ఈమెయిల్ నమోదు చేయండి',
      'short_password': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి',
      'passwords_dont_match': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
      'field_required': 'ఈ ఫీల్డ్ తప్పనిసరి',
      'admin_only': 'అడ్మిన్ వీక్షణ. ఇక్కడ సిలబస్ ఆస్తులను నిర్వహించండి.',
      'user_name': 'విద్యార్థి ప్రొఫైల్',
      'streak_active': 'స్ట్రీక్ సక్రియంగా ఉంది!',
      'back_to_dashboard': 'తిరిగి డాష్‌బోర్డ్‌కు',
      'next': 'తరువాతి',
      'previous': 'మునుపటి',
    }
  };

  String translate(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }
}
